//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_EF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Examinations = new HashSet<Examination>();
            this.Materials = new HashSet<Material>();
            this.TraineeCourseEnrollments = new HashSet<TraineeCourseEnrollment>();
        }
    
        public int ID { get; set; }
        public string CourseName { get; set; }
    
        public virtual ICollection<Examination> Examinations { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<TraineeCourseEnrollment> TraineeCourseEnrollments { get; set; }
    }
}
