//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_EF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public Examination()
        {
            this.Questions = new HashSet<Question>();
            this.TraineeExamEnrollments = new HashSet<TraineeExamEnrollment>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public int CutOffMark { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<TraineeExamEnrollment> TraineeExamEnrollments { get; set; }
    }
}
