//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_EF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Choices = new HashSet<Choice>();
        }
    
        public int ID { get; set; }
        public string QuestionDescription { get; set; }
        public Nullable<int> CorrectAnsID { get; set; }
        public int ExaminationID { get; set; }
    
        public virtual ICollection<Choice> Choices { get; set; }
        public virtual Examination Examination { get; set; }
    }
}
