//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_EF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeCourseEnrollment
    {
        public int ID { get; set; }
        public string TraineeID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime EnrolledDate { get; set; }
        public Nullable<bool> IsEnrolled { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
