//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_EF1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public Trainee()
        {
            this.TraineeCourseEnrollments = new HashSet<TraineeCourseEnrollment>();
            this.TraineeExamEnrollments = new HashSet<TraineeExamEnrollment>();
        }
    
        public string ID { get; set; }
        public string TraineeName { get; set; }
    
        public virtual ICollection<TraineeCourseEnrollment> TraineeCourseEnrollments { get; set; }
        public virtual ICollection<TraineeExamEnrollment> TraineeExamEnrollments { get; set; }
    }
}
